export const data = [
  {
    img: "@/assets/logo.png",
    nom: "chaouch nizar",
    projet: "web",
    mail: "gmail@gmail.com",
    tel: 52641659,
    dated: "20/06/2023",
    datef: "20/07/2023",
    dureestage: "un mois",
    encadrant: "encadrant",
    type: "type de stage",
    status: "desactive",
    niveau: "4eme genie logiciel",
  },
  {
    img: "@/assets/logo.png",
    nom: "nizar",
    projet: "web",
    mail: "gmail@gmail.com",
    tel: 52641659,
    dated: "20/06/2023",
    datef: "20/07/2023",
    dureestage: "un mois",
    encadrant: "encadrant",
    type: "type de stage",
    status: "active",
    niveau: "4eme genie logiciel",
  },
  {
    img: "@/assets/logo.png",
    nom: "nizar",
    projet: "mobile",
    mail: "gmail@gmail.com",
    tel: 52641659,
    dated: "20/06/2023",
    datef: "20/07/2023",
    dureestage: "un mois",
    encadrant: "encadrant",
    type: "type de stage",
    status: "active",
    niveau: "4eme genie logiciel",
  },
  {
    img: "@/assets/logo.png",
    nom: "nizar",
    projet: "mobile",
    mail: "gmail@gmail.com",
    tel: 52641659,
    dated: "20/06/2023",
    datef: "20/07/2023",
    dureestage: "un mois",
    encadrant: "encadrant",
    type: "type de stage",
    status: "active",
    niveau: "4eme genie logiciel",
  },
  {
    img: "@/assets/logo.png",
    nom: "nizar",
    projet: "web",
    mail: "gmail@gmail.com",
    tel: 52641659,
    dated: "20/06/2023",
    datef: "20/07/2023",
    dureestage: "un mois",
    encadrant: "encadrant",
    type: "type de stage",
    status: "desactive",
    niveau: "4eme genie logiciel",
  },
];
