export const data = [
  // {
  //   img: "https://2cm.es/sujL",
  //   nom: "Eya triki",
  //   projet: "Back-end",
  //   mail: "eya@gmail.com",
  //   tel: 52641659,
  //   dated: "1/07/2023",
  //   datef: "5/09/2023",
  //   dureestage: "deux mois",
  //   encadrant: "Loulou",
  //   type: "type de stage",
  //   status: "desactive",
  //   niveau: "4eme genie logiciel",
  // },
  {
    img: "https://2cm.es/tPEt",
    nom: "chaouch nizar",
    projet: "web",
    mail: "gmail@gmail.com",
    tel: 52641659,
    dated: "20/06/2023",
    datef: "20/07/2023",
    dureestage: "un mois",
    encadrant: "encadrant",
    type: "type de stage",
    status: "desactive",
    niveau: "4eme genie logiciel",
  },
  {
    img: "https://2cm.es/tPEt",
    nom: "nizar",
    projet: "web",
    mail: "gmail@gmail.com",
    tel: 52641659,
    dated: "20/06/2023",
    datef: "20/07/2023",
    dureestage: "un mois",
    encadrant: "encadrant",
    type: "type de stage",
    status: "active",
    niveau: "4eme genie logiciel",
  },
  {
    img: "https://2cm.es/tPEt",
    nom: "nizar",
    projet: "mobile",
    mail: "gmail@gmail.com",
    tel: 52641659,
    dated: "20/06/2023",
    datef: "20/07/2023",
    dureestage: "un mois",
    encadrant: "encadrant",
    type: "type de stage",
    status: "active",
    niveau: "4eme genie logiciel",
  },
  {
    img: "https://2cm.es/tPEt",
    nom: "nizar",
    projet: "mobile",
    mail: "gmail@gmail.com",
    tel: 52641659,
    dated: "20/06/2023",
    datef: "20/07/2023",
    dureestage: "un mois",
    encadrant: "encadrant",
    type: "type de stage",
    status: "active",
    niveau: "4eme genie logiciel",
  },
  {
    img: "https://2cm.es/tPEt",
    nom: "nizar",
    projet: "web",
    mail: "gmail@gmail.com",
    tel: 52641659,
    dated: "20/06/2023",
    datef: "20/07/2023",
    dureestage: "un mois",
    encadrant: "encadrant",
    type: "type de stage",
    status: "desactive",
    niveau: "4eme genie logiciel",
  },
];
