export const data = [
  {
    img: "https://2cm.es/tPEt",
    nom: "nizar",
    prenom: "chaouch",
    mail: "gmail@gmail.com",
    tel: "superadmin",
    Specialite: "spc",
    stagiaire: "liste stagiaire",
    isChecked: true,
  },
  {
    img: "https://2cm.es/tPEt",
    nom: "mouhamed",
    prenom: "chaouch",
    mail: "gmail@gmail.com",
    tel: "admin",
    Specialite: "spc",
    stagiaire: "liste stagiaire",
    isChecked: true,
  },
  {
    img: "https://2cm.es/tPEt",
    nom: "aymen",
    prenom: "chaouch",
    mail: "gmail@gmail.com",
    tel: "superadmin",
    Specialite: "spc",
    stagiaire: "liste stagiaire",
    isChecked: true,
  },
];
